version: 2

updates:
  - package-ecosystem: gomod
    directories:
      - /
      - /differential
      - /tools
    schedule:
      interval: weekly
      day: monday
      time: "00:00"
      timezone: Australia/Brisbane
    open-pull-requests-limit: 5
    groups:
      tools:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "00:00"
      timezone: Australia/Brisbane
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - "*"
